Train Epoch: 1 [0/60000 (0%)]	Loss: 2.310870
Train Epoch: 1 [10240/60000 (17%)]	Loss: 2.301778
Train Epoch: 1 [20480/60000 (34%)]	Loss: 2.293518
Train Epoch: 1 [30720/60000 (51%)]	Loss: 2.288135
Train Epoch: 1 [40960/60000 (68%)]	Loss: 2.280593
Train Epoch: 1 [51200/60000 (85%)]	Loss: 2.276849
Validation set: Average loss: 2.2681, Accuracy: 2191/10000 (22%)
1 epoch elapsed time : 44.39155912399292
Error in sys.excepthook:
Traceback (most recent call last):
  File "A:\Users\SSY\anaconda3\envs\pytorch-dev-latest\lib\linecache.py", line 74, in checkcache
    stat = os.stat(fullname)
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    main()
  File "main.py", line 47, in main
    classifier.start_train(model_name=args.saved_model_name)
  File "A:\Users\SSY\Documents\GitHub\Pytorch-Base-Environment\Train.py", line 146, in start_train
    self.__train(self.model, self.device, self.train_loader, self.optimizer, epoch, self.scheduler)
  File "A:\Users\SSY\Documents\GitHub\Pytorch-Base-Environment\Train.py", line 70, in __train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "A:\Users\SSY\anaconda3\envs\pytorch-dev-latest\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "A:\Users\SSY\anaconda3\envs\pytorch-dev-latest\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "A:\Users\SSY\anaconda3\envs\pytorch-dev-latest\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "A:\Users\SSY\anaconda3\envs\pytorch-dev-latest\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "A:\Users\SSY\anaconda3\envs\pytorch-dev-latest\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "A:\Users\SSY\anaconda3\envs\pytorch-dev-latest\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "A:\Users\SSY\anaconda3\envs\pytorch-dev-latest\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
